-- Ourpets user features: optional phone + session history
-- Dialect: PostgreSQL (Supabase)
-- Run this in Supabase SQL Editor after supabase.sql and supabase_admin.sql

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  phone text
);

alter table public.user_profiles enable row level security;

drop trigger if exists trg_user_profiles_set_updated_at on public.user_profiles;
create trigger trg_user_profiles_set_updated_at
before update on public.user_profiles
for each row execute procedure public.set_updated_at();

drop policy if exists "users can read own profile" on public.user_profiles;
create policy "users can read own profile"
on public.user_profiles
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "admins can read profiles" on public.user_profiles;
create policy "admins can read profiles"
on public.user_profiles
for select
to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

drop policy if exists "users can insert own profile" on public.user_profiles;
create policy "users can insert own profile"
on public.user_profiles
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "users can update own profile" on public.user_profiles;
create policy "users can update own profile"
on public.user_profiles
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create table if not exists public.user_session_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users (id) on delete cascade,
  event_type text not null, -- login | logout
  is_admin boolean not null default false,
  user_agent text,
  tz text
);

create index if not exists user_session_events_user_id_created_at_idx
on public.user_session_events (user_id, created_at desc);

alter table public.user_session_events enable row level security;

drop policy if exists "users can read own session events" on public.user_session_events;
create policy "users can read own session events"
on public.user_session_events
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "admins can read session events" on public.user_session_events;
create policy "admins can read session events"
on public.user_session_events
for select
to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

drop policy if exists "users can insert own session events" on public.user_session_events;
create policy "users can insert own session events"
on public.user_session_events
for insert
to authenticated
with check (user_id = auth.uid());
