-- Ourpets demo table for contact/booking submissions.
-- Run this in Supabase SQL Editor.

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null,
  phone text,
  email text,
  pet_type text not null,
  service text not null,
  preferred_date date,
  message text,
  source text
);

alter table public.inquiries enable row level security;

-- Allow anyone (anon) to insert for a demo contact form.
-- For production, restrict by captcha / auth / edge function, etc.
create policy "anon can insert inquiries"
on public.inquiries
for insert
to anon
with check (true);

