-- Ourpets admin + editable services catalog.
-- Run this in Supabase SQL Editor (after supabase.sql).

-- Editable services shown on the public site
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text not null,
  description text not null,
  icon text not null default 'paw', -- paw | grooming | medical | training
  is_active boolean not null default true,
  sort_order int not null default 100
);

create index if not exists services_sort_order_idx on public.services (sort_order);

-- Auto-update updated_at on row update
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_services_set_updated_at on public.services;
create trigger trg_services_set_updated_at
before update on public.services
for each row execute procedure public.set_updated_at();

alter table public.services enable row level security;

-- Site photos (admin-managed images used by sections)
create table if not exists public.site_photos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  section text not null, -- hero | products | tips | services | contact | other
  title text,
  url text not null, -- can be relative (e.g. images/p4.png) or absolute
  is_active boolean not null default true,
  sort_order int not null default 100
);

create index if not exists site_photos_section_sort_order_idx on public.site_photos (section, sort_order);

drop trigger if exists trg_site_photos_set_updated_at on public.site_photos;
create trigger trg_site_photos_set_updated_at
before update on public.site_photos
for each row execute procedure public.set_updated_at();

alter table public.site_photos enable row level security;

-- Admin users table (simple allowlist)
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- Public can read active services
drop policy if exists "public can read active services" on public.services;
create policy "public can read active services"
on public.services
for select
to anon, authenticated
using (is_active = true);

-- Admins can read inquiries (contact/booking submissions)
drop policy if exists "admins can read inquiries" on public.inquiries;
create policy "admins can read inquiries"
on public.inquiries
for select
to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

-- Admins can read ALL services (including inactive)
drop policy if exists "admins can read services" on public.services;
create policy "admins can read services"
on public.services
for select
to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

-- Public can read active site photos
drop policy if exists "public can read active site photos" on public.site_photos;
create policy "public can read active site photos"
on public.site_photos
for select
to anon, authenticated
using (is_active = true);

-- Admins can read/insert/update/delete site photos
drop policy if exists "admins can read site photos" on public.site_photos;
create policy "admins can read site photos"
on public.site_photos
for select
to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

drop policy if exists "admins can insert site photos" on public.site_photos;
create policy "admins can insert site photos"
on public.site_photos
for insert
to authenticated
with check (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

drop policy if exists "admins can update site photos" on public.site_photos;
create policy "admins can update site photos"
on public.site_photos
for update
to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

drop policy if exists "admins can delete site photos" on public.site_photos;
create policy "admins can delete site photos"
on public.site_photos
for delete
to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

-- Supabase Storage bucket for uploaded images (optional)
do $$
begin
  if to_regclass('storage.buckets') is null or to_regclass('storage.objects') is null then
    raise notice 'storage schema not found; skipping Storage bucket/policies';
    return;
  end if;

  insert into storage.buckets (id, name, public)
  values ('ourpets', 'ourpets', true)
  on conflict (id) do nothing;

  -- Public can read ourpets bucket objects (bucket is public, but policy helps for SQL validation)
  begin
    execute 'drop policy if exists "public can read ourpets bucket" on storage.objects';
    execute $p$
      create policy "public can read ourpets bucket"
      on storage.objects
      for select
      to anon, authenticated
      using (bucket_id = 'ourpets')
    $p$;
  exception when others then
    raise notice 'could not create public storage policy: %', sqlerrm;
  end;

  -- Admins can upload/update/delete in ourpets bucket
  begin
    execute 'drop policy if exists "admins can insert ourpets bucket" on storage.objects';
    execute $p$
      create policy "admins can insert ourpets bucket"
      on storage.objects
      for insert
      to authenticated
      with check (
        bucket_id = 'ourpets'
        and exists (select 1 from public.admin_users au where au.user_id = auth.uid())
      )
    $p$;

    execute 'drop policy if exists "admins can update ourpets bucket" on storage.objects';
    execute $p$
      create policy "admins can update ourpets bucket"
      on storage.objects
      for update
      to authenticated
      using (
        bucket_id = 'ourpets'
        and exists (select 1 from public.admin_users au where au.user_id = auth.uid())
      )
      with check (
        bucket_id = 'ourpets'
        and exists (select 1 from public.admin_users au where au.user_id = auth.uid())
      )
    $p$;

    execute 'drop policy if exists "admins can delete ourpets bucket" on storage.objects';
    execute $p$
      create policy "admins can delete ourpets bucket"
      on storage.objects
      for delete
      to authenticated
      using (
        bucket_id = 'ourpets'
        and exists (select 1 from public.admin_users au where au.user_id = auth.uid())
      )
    $p$;
  exception when others then
    raise notice 'could not create admin storage policies: %', sqlerrm;
  end;
end;
$$;

-- Admin check helper (inline EXISTS in policies)
-- Admins can insert/update/delete services
drop policy if exists "admins can insert services" on public.services;
create policy "admins can insert services"
on public.services
for insert
to authenticated
with check (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

drop policy if exists "admins can update services" on public.services;
create policy "admins can update services"
on public.services
for update
to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

drop policy if exists "admins can delete services" on public.services;
create policy "admins can delete services"
on public.services
for delete
to authenticated
using (exists (select 1 from public.admin_users au where au.user_id = auth.uid()));

-- Let logged-in users check whether THEY are admin (self row only)
drop policy if exists "users can read own admin row" on public.admin_users;
create policy "users can read own admin row"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

-- Seed demo site photos (safe to rerun)
insert into public.site_photos (section, title, url, is_active, sort_order)
select 'hero', 'Hero image', 'images/Pet care store interior display.png', true, 10
where not exists (select 1 from public.site_photos where section = 'hero');

insert into public.site_photos (section, title, url, is_active, sort_order)
select 'products', 'Product image 1', 'images/p4.png', true, 10
where not exists (select 1 from public.site_photos where section = 'products' and url = 'images/p4.png');

insert into public.site_photos (section, title, url, is_active, sort_order)
select 'products', 'Product image 2', 'images/p5.png', true, 20
where not exists (select 1 from public.site_photos where section = 'products' and url = 'images/p5.png');

insert into public.site_photos (section, title, url, is_active, sort_order)
select 'products', 'Product image 3', 'images/p6.png', true, 30
where not exists (select 1 from public.site_photos where section = 'products' and url = 'images/p6.png');

-- Seed demo services (safe to rerun)
insert into public.services (title, description, icon, is_active, sort_order)
select 'Gentle Grooming', 'Bath, brush, trim - with treats, calm music, and cozy towels.', 'grooming', true, 10
where not exists (select 1 from public.services where title = 'Gentle Grooming');

insert into public.services (title, description, icon, is_active, sort_order)
select 'Vet-Friendly Essentials', 'Care products chosen for sensitive skin and waggy comfort.', 'medical', true, 20
where not exists (select 1 from public.services where title = 'Vet-Friendly Essentials');

insert into public.services (title, description, icon, is_active, sort_order)
select 'Happy Training', 'Tiny steps, big cheers - positive reinforcement starter sessions.', 'training', true, 30
where not exists (select 1 from public.services where title = 'Happy Training');
